### ISSUE TITLE
Cannot compile Gatekeeper - Not reading

### ISSUE THREAD

**Issue by quacksawbones** [germinateplatform/germinate-gatekeeper#1]
Have cloned the current version of Germinate onto our server. Tried to compile using `ant`, but received the following message:

`gwtc:
     [java] Loading inherited module '${project.root}'
     [java]    [ERROR] Invalid module name: '${project.root}'

BUILD FAILED
<path..to>/germinate-gatekeeper/build.xml:52: Java returned: 1`

Need to modify the `build.xml` file and change `<property file="build-dev.properties"/>` to `<property file="build.properties"/>`

**Comment by sebastian-raubach** [comment]
Yes, we're aware of this. It's due to the fact, that the `build.properties` need to be checked in to Github, but we're locally using `build-dev.properties` when building. Since `build.properties` never changes and we don't want to commit our local copies, but `build.xml` changes quite frequently it's the most convenient way for us to handle this situation.
If we were to point `build.xml` at `build.properties`, we'd have to change it every time locally before we commit to Github to make sure it works.
It's not ideal, but we haven't found a better solution yet.

**Comment by sebastian-raubach** [comment]
The same is true for `config.properties`, i.e. `config-dev.properties`.

**Comment by sebastian-raubach** [comment]
Just did some research and the way we do it is actually one of the recommended ways of doing it (just the other way around).
https://gist.github.com/canton7/1423106

We'll probably keep doing it this way, but try and make it clearer that files need to be renamed before Germinate and Gatekeeper can be built.
